# Generated by Django 6.0.3 on 2026-03-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
