# Generated by Django 6.0.3 on 2026-03-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('games', 'Games'), ('apps', 'Apps'), ('tools', 'Tools')], default='apps', max_length=20),
        ),
    ]
